### PR TITLE
Add libra(Mi-4c)

### PR DESCRIPTION
**Pull request by viscropst**

### CODE REVIEW

**Comment by akhilnarang** [comment]
@viscropst No?

**Comment by akhilnarang** [comment]
@viscropst No new devices are being accepted at this time. And anyway, patch should've been pushed to Gerrit.

**Comment by viscropst** [comment]
Oh,Sorry I don't know this.Please give me address of gerrit to contribute it.

**Comment by akhilnarang** [comment]
@viscropst review.aosiprom.com

**Comment by viscropst** [comment]
@akhilnarang  Thanks,I'll upload to gerrit.

**Pull request closed without merging**
