### PR TITLE
Add Titan

### PR DESCRIPTION
**Pull request by kranone124**

### CODE REVIEW

**Comment by mikecriggs** [comment]
Please push all proposed changes to Gerrit.
It's here: review.aosip.xyz

If you need help pushing to Gerrit, see the included documentation provided on the page.

Thank you.

**Comment by kranone124** [comment]
ok thanks i push it over gerrit

**Comment by mikecriggs** [comment]
@akhilnarang @xlxfoxxlx Can one of you guys close this?

**Comment by akhilnarang** [comment]
Oops, didn't see it

**Pull request closed without merging**
