### PR TITLE
Update aosip_oneplus3.mk

### PR DESCRIPTION
**Pull request by ChuckDaEngineer**
Add unofficial maintainer.

### CODE REVIEW

**Comment by msfjarvis** [comment]
@ChuckDaEngineer doesn't work that way

**Comment by BoredOutOfMyGit** [comment]
Hahhaa he thinks is RR where they accept randoms as maintainers

**Comment by ChuckDaEngineer** [comment]
Yup, my bad. First try at a change to my own tree. Back to the tutorial. Can I withdraw this pull request?

**Comment by msfjarvis** [comment]
Just hit close

**Comment by ChuckDaEngineer** [comment]
Acknowledged. TNX.

**Comment by Dabug123** [comment]
Why have u forked the whole ROM furthermore why did u change maintainer and where do u think u are posting these ,because let's go ahead get this done..We do not want unofficial anything on XDA

**Pull request closed without merging**
